# Generated by Django 6.0.5 on 2026-05-14 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='', max_length=2000)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('device_type', models.CharField(blank=True, default='', max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='links.link')),
            ],
            options={
                'db_table': 'analytics_clickevent',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['link', '-clicked_at'], name='analytics_c_link_id_ff89ee_idx'), models.Index(fields=['clicked_at'], name='analytics_c_clicked_ca1c42_idx'), models.Index(fields=['link', 'device_type'], name='analytics_c_link_id_9d6ef0_idx')],
            },
        ),
    ]
