# Generated by Django 6.0.5 on 2026-05-14 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.TextField()),
                ('short_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('custom_alias', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'links_link',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='links_link_short_c_886f39_idx'), models.Index(fields=['owner', '-created_at'], name='links_link_owner_i_d4ad2a_idx'), models.Index(fields=['status'], name='links_link_status_dfcd38_idx')],
            },
        ),
    ]
